<?xml version="1.0" encoding="UTF-8"?>
<!--DTD schema-->
<!DOCTYPE Cards [
    <!ELEMENT Cards (Card+) >
    <!ELEMENT Card (name, description, players, rules) >
    <!ELEMENT rules (rule+) >
    <!ELEMENT rule (statements, effect) >
    <!ELEMENT name (#PCDATA) >
    <!ELEMENT description (#PCDATA) >
    <!ELEMENT players (#PCDATA) >
    <!ELEMENT statements ((if | nif)+) >
    <!ELEMENT effect (type, subtype?, data?, nextstate?) >
    <!ELEMENT type (#PCDATA) >
    <!ELEMENT data (#PCDATA) >
    <!ELEMENT nextstate (#PCDATA)>
    <!ELEMENT subtype (#PCDATA)>
    <!ELEMENT if (subject, verb, object) >
    <!ELEMENT nif (subject, verb, object) >
    <!ELEMENT subject (#PCDATA)>
    <!ELEMENT verb (#PCDATA)>
    <!ELEMENT object (#PCDATA)>
    <!ATTLIST rule
        event (MOVE | BUILD) #REQUIRED >
]>
<!--Cards-->
<Cards>
    <Card>
        <name>Apollo</name>
        <description>
            Your Move: Your Worker may move into an opponent Workerâ€™s space by forcing their Worker to the space yours just vacated.
        </description>
        <players>2,3</players>
        <rules>
            <rule event="MOVE">
                <statements>
                    <if> <!--Sei il possessore della carta-->
                        <subject>YOU</subject>
                        <verb>PLAYER_EQUALS</verb>
                        <object>CARD_OWNER</object>
                    </if>
                    <if> <!--Hai un'interazione con un altro worker-->
                        <subject>YOU</subject>
                        <verb>INTERACTION_NUM</verb>
                        <object>1</object>
                    </if>
                    <if> <!--Quell'unica interazione era nella posizione finale ed era un avversario-->
                        <subject>FINAL_POSITION</subject>
                        <verb>POSITION_EQUALS</verb>
                        <object>OPPONENTS</object>
                    </if>
                </statements>
                <effect> <!--Sposta l'avversario al tuo posto-->
                    <type>ALLOW</type>
                </effect>
            </rule>
        </rules>
    </Card>
</Cards>
